apiVersion: v1
kind: Service
metadata:
  name: chai-com
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0873ddd9ce8cc67eb,subnet-0d620cbc2a6943321,subnet-0d1ffbc6717505f3a"
spec:
  type: LoadBalancer
  selector:
    app: chai-com
  ports:
    - port: 80
      targetPort: 3000
